language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "Image build is about to begin!"

# Scripts to be run such as tests
before_script:
  - echo "no tests needed for now!"

script:
  - docker --version # print the version for logging
  - echo "Building udagram-api-user"
  - docker-compose -f docker-compose-build.yaml build --parallel 
  - echo "udagram-frontend build complete"
  - echo "Image build successful"

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_USERNAME/udagram-api-user:latest
  - docker push $DOCKER_USERNAME/udagram-api-feed:latest
  - docker $DOCKER_USERNAME/reverseproxy:latest
  - docker $DOCKER_USERNAME/udagram-frontend:latest

