apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: udagram-frontend
  name: udagram-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: udagram-frontend
        api: external
    spec:
      containers:
      - image: manpasu/udagram-frontend:v5
        name: udagram-frontend
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 250m
        envFrom:
        - configMapRef:
            name: k-configmap
        resources: {}
status: {}
