apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: udagram-reverseproxy
  name: udagram-reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-reverseproxy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: udagram-reverseproxy
    spec:
      containers:
      - image: manpasu/udagram-reverseproxy:v3
        name: udagram-reverseproxy
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 250m
    
